// <auto-generated />
using System;
using BlazorApp1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorApp1.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260528152324_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlazorApp1.Data.QuoteDataSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("QuoteDataSets");
                });

            modelBuilder.Entity("BlazorApp1.Data.StockQuote", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Close")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("DataSetId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("High")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Low")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<double?>("Ma10")
                        .HasColumnType("float");

                    b.Property<double?>("Ma5")
                        .HasColumnType("float");

                    b.Property<double?>("MacdHistogram")
                        .HasColumnType("float");

                    b.Property<double?>("MacdSignal")
                        .HasColumnType("float");

                    b.Property<double?>("MacdValue")
                        .HasColumnType("float");

                    b.Property<decimal>("Open")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<double?>("Rsi14")
                        .HasColumnType("float");

                    b.Property<double?>("Sma20")
                        .HasColumnType("float");

                    b.Property<double?>("Stoch2D")
                        .HasColumnType("float");

                    b.Property<double?>("Stoch2K")
                        .HasColumnType("float");

                    b.Property<double?>("StochD")
                        .HasColumnType("float");

                    b.Property<double?>("StochK")
                        .HasColumnType("float");

                    b.Property<double?>("StochRsi")
                        .HasColumnType("float");

                    b.Property<double?>("StochRsiSignal")
                        .HasColumnType("float");

                    b.Property<decimal>("Volume")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("DataSetId", "Date")
                        .IsUnique();

                    b.ToTable("StockQuotes");
                });

            modelBuilder.Entity("BlazorApp1.Data.StockQuote", b =>
                {
                    b.HasOne("BlazorApp1.Data.QuoteDataSet", "DataSet")
                        .WithMany("Quotes")
                        .HasForeignKey("DataSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DataSet");
                });

            modelBuilder.Entity("BlazorApp1.Data.QuoteDataSet", b =>
                {
                    b.Navigation("Quotes");
                });
#pragma warning restore 612, 618
        }
    }
}
